### ISSUE TITLE
USER STORY: Site Pagination

### ISSUE THREAD

**Issue by RubemJanoni** [RubemJanoni/Django-Blog#2]
EPIC:<epic>

As a **Site User** I can **view a list of posts** so that **I can select one to read**

**Acceptance criteria**

- [ ] #13
- [ ] The can add as many ingredients as needed.

**Tasks**

- [ ] Task1: Design and implement new recipe item
- [ ] Task2: Implement recipe upload funcionality
